- name: Webhook site events
  hosts: localhost
  sources:
    - name: Webhook.site POSTs as events
      webhooksite:
        api_url: "{{ api_url }}"
        interval: 10

  rules:
    - name: R1 - New webhook.site POST with content
      condition: |
        event.state == "1"
      action:
        debug:
