- name: Webhook site events2
  hosts: localhost
  sources:
    - name: Webhook.site POSTs as events
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: R1 - New webhook.site POST with content
      condition: |
        event.state == "1"
      action:
        debug:
